#ifndef ISR_PRIORITIES_H_
#define ISR_PRIORITIES_H_

#define ISR_PRIORITY_ASCLIN0_RX 15
#define ISR_PRIORITY_ASCLIN0_TX 16
#define ISR_PRIORITY_ASCLIN1_RX 25

#define ISR_PRIORITY_ERU_INT0 14

#define ISR_PRIORITY_GPT1T3_TIMER 20
#define ISR_PRIORITY_GPT2T6_TIMER 21

#define ISR_PRIORITY_STM0 50

#define ISR_PRIORITY_CAN_TX 52
#define ISR_PRIORITY_CAN_RX 51

#endif /* ISR_PRIORITIES_H_ */
