#ifndef PRIORITY_H_
#define PRIORITY_H_

#define ISR_PRIORITY_ATOM   21

#define ISR_PRIORITY_ASCLIN0_RX 15
#define ISR_PRIORITY_ASCLIN0_TX 16
#define ISR_PRIORITY_ASCLIN1_RX 25

#define ISR_PRIORITY_ERU_INT0 14

#define ISR_PRIORITY_ULTRASONIC 13
#define ISR_PRIORITY_ULTRASONIC_TRIGGER 30

#define ISR_PRIORITY_GPT1T3_TIMER 8
#define ISR_PRIORITY_GPT2T6_TIMER 9

#define ISR_PRIORITY_STM0 50


#define ISR_PRIORITY_CAN_TX 52
#define ISR_PRIORITY_CAN_RX 51

#endif /* PRIORITY_H_ */
